version: "3.7"
services:
  trusticket-booking-database:
    platform: linux/x86_64
    image: mariadb:10.11.2
    environment:
      MYSQL_DATABASE: "trusticket-booking-db"
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - 4004:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

 